"""xwa_sdk — shared data models and validation for the XWA ecosystem."""

from .models import (
    ANALYSIS_STATUS,
    EVENT_TYPES,
    SEVERITIES,
    TOOLS,
    Analysis,
    ApiEndpoint,
    Cdn,
    Challenge,
    DiscoveredLink,
    DiscoveredRoute,
    Error,
    Event,
    Finding,
    JsDependency,
    RateLimit,
    Summary,
    Technology,
    Waf,
    from_dict,
    map_severity,
    to_dict,
)
from .validation import (
    ITEM_KINDS,
    ValidationError,
    is_valid_analysis,
    is_valid_error,
    is_valid_event,
    is_valid_finding,
    is_valid_item,
    validate_analysis,
    validate_error,
    validate_event,
    validate_finding,
    validate_item,
)

__version__ = "0.2.0"

__all__ = [
    "TOOLS",
    "ANALYSIS_STATUS",
    "SEVERITIES",
    "EVENT_TYPES",
    "ITEM_KINDS",
    "Analysis",
    "Finding",
    "Event",
    "Error",
    "Summary",
    "DiscoveredLink",
    "Technology",
    "DiscoveredRoute",
    "JsDependency",
    "Waf",
    "Cdn",
    "Challenge",
    "RateLimit",
    "ApiEndpoint",
    "to_dict",
    "from_dict",
    "map_severity",
    "validate_analysis",
    "validate_finding",
    "validate_event",
    "validate_error",
    "validate_item",
    "is_valid_analysis",
    "is_valid_finding",
    "is_valid_event",
    "is_valid_error",
    "is_valid_item",
    "ValidationError",
    "__version__",
]
